# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=20)),
                ('pwd', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('picture', models.ImageField(null=True, upload_to='studygroups')),
                ('info', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='study_groups',
            field=models.ManyToManyField(to='coin.StudyGroup'),
        ),
    ]
