# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AddField(
            model_name='student',
            name='face_id',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='person_id',
            field=models.CharField(default=0, max_length=60, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='picture',
            field=models.ImageField(null=True, upload_to='students'),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='slack_id',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
    ]
