# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 03:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0005_studygroup_processed_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studygroup',
            name='processed_pic',
        ),
    ]
