# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 07:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0006_remove_studygroup_processed_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='face_id',
            new_name='slack_id',
        ),
        migrations.RemoveField(
            model_name='studygroup',
            name='slack_id',
        ),
    ]
