# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0007_auto_20171008_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='present',
            field=models.BooleanField(default=False),
        ),
    ]
